# language: node_js
# sudo: required
# node_js:
#   - "stable"
# cache:
#   directories:
#     - node_modules
# script:
#   - ./deploy-travis.sh
# branch: master

# language: node_js
# node_js:
#   - lts/*
# script:
#   - yarn build
# deploy:
#   provider: pages
#   skip-cleanup: true
#   local_dir: dist
#   github-token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
#   keep-history: true
#   on:
#     branch: master

language: node_js
node_js:
  - "10"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install:
  - npm install -g vuepress
script:
  - npm run build
cache:
  directories:
    - "node_modules"
notifications:
  email: false
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: dist
  github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  repo: steakxiaoxin/vuepress
  keep-history: true
  target-branch: master
  on:
    branch: master
