# language: node_js
# sudo: required
# node_js:
#   - "stable"
# cache:
#   directories:
#     - node_modules
# script:
#   - ./deploy-travis.sh
# branch: master

language: node_js
node_js:
  - lts/*
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: dist
  github-token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
  keep-history: true
  on:
    branch: master
